# Generated by Django 3.0.2 on 2021-10-13 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this field is required', max_length=124)),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('unid', models.SlugField(blank=True, max_length=124)),
                ('draft', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('changed', models.DateField(auto_now=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload_post_img')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='List of tags separated by comma', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
