# Generated by Django 3.0.2 on 2021-10-13 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.CharField(blank=True, max_length=8, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('born', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=56)),
                ('last_name', models.CharField(blank=True, default='', max_length=124)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_avatar)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
